In [333]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/dataset-property-category-uas/financial Property and category .csv

In [334]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
import matplotlib as mpl
import matplotlib.pyplot as plt



import statsmodels.api as sm

# readable figures
pd.set_option('float_format', '{:f}'.format)

In [335]:
df = pd.read_csv('../input/dataset-property-category-uas/financial Property and category .csv')
df.head()

  Emitten      DER       ROA  Sales Growth       ROE       NPM  Category
0    AMAN 0.400000  0.010000     -3.797435  0.010000  0.180000         3
1    APLN 1.790000 -0.020000     18.184296 -0.060000 -0.210000         2
2    ASRI 1.350000 -0.010000    669.231018 -0.020000 -0.090000         2
3    ATAP 0.240000  0.050000     35.698101  0.070000  0.110000         3
4    BAPA 0.070000 -0.030000     -3.317679 -0.030000 -1.140000         4

In [336]:
df.describe()

            DER       ROA  Sales Growth       ROE       NPM  Category
count 17.000000 17.000000     17.000000 17.000000 17.000000 17.000000
mean   0.722941  0.007647    308.727609  0.015882 -0.053529  3.000000
std    0.527017  0.045073    830.480254  0.069377  0.935127  1.000000
min    0.070000 -0.060000   -546.164778 -0.150000 -1.860000  1.000000
25%    0.400000 -0.020000    -26.572531 -0.020000 -0.370000  2.000000
50%    0.610000 -0.010000     -3.317679  0.010000  0.110000  3.000000
75%    1.140000  0.030000     35.698101  0.050000  0.420000  4.000000
max    1.790000  0.130000   2408.626000  0.150000  2.000000  5.000000

In [337]:
display(df)

   Emitten      DER       ROA  Sales Growth       ROE       NPM  Category
0     AMAN 0.400000  0.010000     -3.797435  0.010000  0.180000         3
1     APLN 1.790000 -0.020000     18.184296 -0.060000 -0.210000         2
2     ASRI 1.350000 -0.010000    669.231018 -0.020000 -0.090000         2
3     ATAP 0.240000  0.050000     35.698101  0.070000  0.110000         3
4     BAPA 0.070000 -0.030000     -3.317679 -0.030000 -1.140000         4
5     BAPI 0.470000 -0.010000     -0.096221 -0.010000 -1.430000         4
6     BCIP 1.140000 -0.010000    -46.929469 -0.010000 -0.160000         2
7     BEST 0.420000 -0.020000    -84.809916 -0.030000 -1.030000         4
8     BKDP 0.730000 -0.050000     -9.498563  0.040000  0.160000         2
9     BKSL 0.610000  0.020000   2374.304900  0.040000  0.420000         3
10    BSDE 0.690000  0.020000     -7.213595  0.070000  2.000000         3
11    CPRI 0.130000 -0.010000      0.820829 -0.010000 -0.370000         4
12    CTRA 1.160000  0.050000   2408.626000  0.110000  0.320000         3
13    DADA 1.000000  0.030000   -182.316900  0.050000  0.730000         3
14    DART 1.570000 -0.060000    -26.572531 -0.150000 -1.860000         5
15    DMAS 0.120000  0.130000    652.221301  0.150000  0.650000         1
16    DUTI 0.400000  0.040000   -546.164778  0.050000  0.810000         3

In [338]:
x = df.drop(['Category','Emitten'], axis=1)
x.head()

       DER       ROA  Sales Growth       ROE       NPM
0 0.400000  0.010000     -3.797435  0.010000  0.180000
1 1.790000 -0.020000     18.184296 -0.060000 -0.210000
2 1.350000 -0.010000    669.231018 -0.020000 -0.090000
3 0.240000  0.050000     35.698101  0.070000  0.110000
4 0.070000 -0.030000     -3.317679 -0.030000 -1.140000

In [339]:
y = df['Category']
y.head()

0    3
1    2
2    2
3    3
4    4
Name: Category, dtype: int64

In [340]:
from sklearn.preprocessing import StandardScaler 
from sklearn import preprocessing
x_scaled = StandardScaler().fit_transform(x)
data_scaled = pd.DataFrame(x_scaled, columns=df.columns.drop(['Emitten','Category']))

data_scaled

         DER       ROA  Sales Growth       ROE       NPM
0  -0.631631  0.053809     -0.387900 -0.087397  0.257416
1   2.087027 -0.632255     -0.360617 -1.127423 -0.172475
2   1.226445 -0.403567      0.447450 -0.533122 -0.040201
3  -0.944570  0.968561     -0.338879  0.804053  0.180256
4  -1.277067 -0.860943     -0.387305 -0.681697 -1.197601
5  -0.494720 -0.403567     -0.383306 -0.384547 -1.517263
6   0.815712 -0.403567     -0.441435 -0.384547 -0.117361
7  -0.592513 -0.632255     -0.488451 -0.681697 -1.076349
8   0.013806 -1.318319     -0.394976  0.358328  0.235370
9  -0.220898  0.282497      2.563756  0.358328  0.521965
10 -0.064429  0.282497     -0.392140  0.804053  2.263575
11 -1.159715 -0.403567     -0.382168 -0.384547 -0.348841
12  0.854830  0.968561      2.606354  1.398354  0.411736
13  0.541891  0.511185     -0.609475  0.506903  0.863673
14  1.656736 -1.547007     -0.416168 -2.464598 -1.991246
15 -1.179274  2.798066      0.426338  1.992654  0.775490
16 -0.631631  0.739873     -1.061076  0.506903  0.951856

In [341]:
display(df)

   Emitten      DER       ROA  Sales Growth       ROE       NPM  Category
0     AMAN 0.400000  0.010000     -3.797435  0.010000  0.180000         3
1     APLN 1.790000 -0.020000     18.184296 -0.060000 -0.210000         2
2     ASRI 1.350000 -0.010000    669.231018 -0.020000 -0.090000         2
3     ATAP 0.240000  0.050000     35.698101  0.070000  0.110000         3
4     BAPA 0.070000 -0.030000     -3.317679 -0.030000 -1.140000         4
5     BAPI 0.470000 -0.010000     -0.096221 -0.010000 -1.430000         4
6     BCIP 1.140000 -0.010000    -46.929469 -0.010000 -0.160000         2
7     BEST 0.420000 -0.020000    -84.809916 -0.030000 -1.030000         4
8     BKDP 0.730000 -0.050000     -9.498563  0.040000  0.160000         2
9     BKSL 0.610000  0.020000   2374.304900  0.040000  0.420000         3
10    BSDE 0.690000  0.020000     -7.213595  0.070000  2.000000         3
11    CPRI 0.130000 -0.010000      0.820829 -0.010000 -0.370000         4
12    CTRA 1.160000  0.050000   2408.626000  0.110000  0.320000         3
13    DADA 1.000000  0.030000   -182.316900  0.050000  0.730000         3
14    DART 1.570000 -0.060000    -26.572531 -0.150000 -1.860000         5
15    DMAS 0.120000  0.130000    652.221301  0.150000  0.650000         1
16    DUTI 0.400000  0.040000   -546.164778  0.050000  0.810000         3

In [342]:
trainX, testX, trainY, testY = train_test_split(x, y, test_size = 0.3)

In [343]:
mnlogit_mod = sm.MNLogit(y,sm.add_constant(data_scaled))
mnlogit_fit = mnlogit_mod.fit(method='bfgs')

print (mnlogit_fit.summary())

Optimization terminated successfully.
         Current function value: 0.000009
         Iterations: 24
         Function evaluations: 25
         Gradient evaluations: 25

/opt/conda/lib/python3.7/site-packages/statsmodels/base/model.py:593: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)

ValueError: need covariance of parameters for computing (unnormalized) covariances

In [ ]:
logistic_regresion = LogisticRegression(multi_class='auto').fit(x,y)
y_pred = logistic_regresion.predict(testX)
y_pred

In [ ]:
print('Intercept :', logistic_regresion.intercept_)

In [ ]:
print(logistic_regresion.coef_)

In [ ]:
prediction_test = logistic_regresion.predict(testX)

In [ ]:
print('Accuracy: {:.2f}'.format(accuracy_score(testY, y_pred)))
print('Error rate: {:.2f}'.format(1 - accuracy_score(testY, y_pred)))

In [ ]:
confusion_matrix = confusion_matrix(testY, y_pred)
print(confusion_matrix)

In [ ]:
plt.matshow(confusion_matrix, cmap=plt.cm.gray)
plt.show()

In [344]:
probability = logistic_regresion.predict_proba(testX)
probability

array([[0.081823  , 0.16752878, 0.46204634, 0.24261698, 0.04598491],
       [0.0282717 , 0.07061234, 0.06897368, 0.73873693, 0.09340535],
       [0.02529571, 0.62901195, 0.17499235, 0.06351378, 0.10718622],
       [0.0440991 , 0.4206569 , 0.26845695, 0.15845017, 0.10833687],
       [0.0393375 , 0.09140368, 0.86170155, 0.00508133, 0.00247593],
       [0.04990835, 0.31869613, 0.53002575, 0.06083663, 0.04053315]])

In [345]:
print(probability.shape[0])
print(testX.shape[0])

6
6

In [346]:
data_result = pd.DataFrame(logistic_regresion.predict_proba(testX), columns=logistic_regresion.classes_)
data_result

         1        2        3        4        5
0 0.081823 0.167529 0.462046 0.242617 0.045985
1 0.028272 0.070612 0.068974 0.738737 0.093405
2 0.025296 0.629012 0.174992 0.063514 0.107186
3 0.044099 0.420657 0.268457 0.158450 0.108337
4 0.039338 0.091404 0.861702 0.005081 0.002476
5 0.049908 0.318696 0.530026 0.060837 0.040533

In [347]:
data_result['sum'] = data_result.sum(axis=1)
data_result

         1        2        3        4        5      sum
0 0.081823 0.167529 0.462046 0.242617 0.045985 1.000000
1 0.028272 0.070612 0.068974 0.738737 0.093405 1.000000
2 0.025296 0.629012 0.174992 0.063514 0.107186 1.000000
3 0.044099 0.420657 0.268457 0.158450 0.108337 1.000000
4 0.039338 0.091404 0.861702 0.005081 0.002476 1.000000
5 0.049908 0.318696 0.530026 0.060837 0.040533 1.000000

In [348]:
data_result['predicted_class'] = y_pred
data_result

         1        2        3        4        5      sum  predicted_class
0 0.081823 0.167529 0.462046 0.242617 0.045985 1.000000                3
1 0.028272 0.070612 0.068974 0.738737 0.093405 1.000000                3
2 0.025296 0.629012 0.174992 0.063514 0.107186 1.000000                3
3 0.044099 0.420657 0.268457 0.158450 0.108337 1.000000                3
4 0.039338 0.091404 0.861702 0.005081 0.002476 1.000000                3
5 0.049908 0.318696 0.530026 0.060837 0.040533 1.000000                4

In [349]:
data_result['actual_class'] = testY.to_frame().reset_index().drop(columns='index')
data_result

,1,2,3,4,5,sum,predicted_class,actual_class
0,0.081823,0.167529,0.462046,0.242617,0.045985,1.000000,3,3
1,0.028272,0.070612,0.068974,0.738737,0.093405,1.000000,3,4
2,0.025296,0.629012,0.174992,0.063514,0.107186,1.000000,3,2
3,0.044099,0.420657,0.268457,0.158450,0.108337,1.000000,3,2
4,0.039338,0.091404,0.861702,0.005081,0.002476,1.000000,3,3
5,0.049908,0.318696,0.530026,0.060837,0.040533,1.000000,4,3

In [350]:
le = preprocessing.LabelEncoder()

data_result['label_pred'] = le.fit_transform(data_result['predicted_class'])
data_result['label_actual'] = le.fit_transform(data_result['actual_class'])
data_result

,1,2,3,4,5,sum,predicted_class,actual_class,label_pred,label_actual
0,0.081823,0.167529,0.462046,0.242617,0.045985,1.000000,3,3,0,1
1,0.028272,0.070612,0.068974,0.738737,0.093405,1.000000,3,4,0,2
2,0.025296,0.629012,0.174992,0.063514,0.107186,1.000000,3,2,0,0
3,0.044099,0.420657,0.268457,0.158450,0.108337,1.000000,3,2,0,0
4,0.039338,0.091404,0.861702,0.005081,0.002476,1.000000,3,3,0,1
5,0.049908,0.318696,0.530026,0.060837,0.040533,1.000000,4,3,1,1

In [351]:
targets = data_result['predicted_class']   
integerEncoded = le.fit_transform(targets)
integerMapping=dict(zip(targets,integerEncoded))
integerMapping

{3: 0, 4: 1}

In [352]:
targets = data_result['actual_class']   
integerEncoded = le.fit_transform(targets)
integerMapping=dict(zip(targets,integerEncoded))
integerMapping

{3: 1, 4: 2, 2: 0}

In [353]:
data_result['check'] = data_result['label_actual'] - data_result['label_pred']
data_result

,1,2,3,4,5,sum,predicted_class,actual_class,label_pred,label_actual,check
0,0.081823,0.167529,0.462046,0.242617,0.045985,1.000000,3,3,0,1,1
1,0.028272,0.070612,0.068974,0.738737,0.093405,1.000000,3,4,0,2,2
2,0.025296,0.629012,0.174992,0.063514,0.107186,1.000000,3,2,0,0,0
3,0.044099,0.420657,0.268457,0.158450,0.108337,1.000000,3,2,0,0,0
4,0.039338,0.091404,0.861702,0.005081,0.002476,1.000000,3,3,0,1,1
5,0.049908,0.318696,0.530026,0.060837,0.040533,1.000000,4,3,1,1,0

In [354]:
data_result['correct_prediction?'] = np.where(data_result['check'] == 0, 'True', 'False')
data_result = data_result.drop(['label_pred', 'label_actual', 'check'], axis=1)
data_result

,1,2,3,4,5,sum,predicted_class,actual_class,correct_prediction?
0,0.081823,0.167529,0.462046,0.242617,0.045985,1.000000,3,3,False
1,0.028272,0.070612,0.068974,0.738737,0.093405,1.000000,3,4,False
2,0.025296,0.629012,0.174992,0.063514,0.107186,1.000000,3,2,True
3,0.044099,0.420657,0.268457,0.158450,0.108337,1.000000,3,2,True
4,0.039338,0.091404,0.861702,0.005081,0.002476,1.000000,3,3,False
5,0.049908,0.318696,0.530026,0.060837,0.040533,1.000000,4,3,True

In [355]:
display(data_result)

,1,2,3,4,5,sum,predicted_class,actual_class,correct_prediction?
0,0.081823,0.167529,0.462046,0.242617,0.045985,1.000000,3,3,False
1,0.028272,0.070612,0.068974,0.738737,0.093405,1.000000,3,4,False
2,0.025296,0.629012,0.174992,0.063514,0.107186,1.000000,3,2,True
3,0.044099,0.420657,0.268457,0.158450,0.108337,1.000000,3,2,True
4,0.039338,0.091404,0.861702,0.005081,0.002476,1.000000,3,3,False
5,0.049908,0.318696,0.530026,0.060837,0.040533,1.000000,4,3,True

In [356]:
true_predictions = data_result[(data_result["correct_prediction?"] == 'True')].shape[0]
false_predictions = data_result[(data_result["correct_prediction?"] == 'False')].shape[0]
total = data_result["correct_prediction?"].shape[0]

print('manual calculated Accuracy is:', (true_predictions / total * 100))

manual calculated Accuracy is: 50.0

In [357]:
wrong_pred = data_result[(data_result["correct_prediction?"] == 'False')]
wrong_pred

,1,2,3,4,5,sum,predicted_class,actual_class,correct_prediction?
0,0.081823,0.167529,0.462046,0.242617,0.045985,1.000000,3,3,False
1,0.028272,0.070612,0.068974,0.738737,0.093405,1.000000,3,4,False
4,0.039338,0.091404,0.861702,0.005081,0.002476,1.000000,3,3,False

In [358]:
x2 = sm.add_constant(data_scaled, prepend = False)

mnlogit_mod = sm.MNLogit(y, x2).fit(method='bfgs')

print (mnlogit_mod.summary())

Optimization terminated successfully.
         Current function value: 0.000009
         Iterations: 24
         Function evaluations: 25
         Gradient evaluations: 25

/opt/conda/lib/python3.7/site-packages/statsmodels/base/model.py:593: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)

ValueError: need covariance of parameters for computing (unnormalized) covariances